version: '3'

services:
  web:
    build: .
    environment:
      - EMAIL_USER=mail@mail.com
      - EMAIL_PASSWORD=secret
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/blog/
    ports:
      - "8000:8000"