# Generated by Django 2.1.1 on 2018-09-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-timestamp']},
        ),
    ]
